blank_issues_enabled: true
contact_links:
  - name: "🗪  IRC #neomutt on irc.libera.chat"
    url: https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt
    about: Chat with NeoMutt users
  - name: "🖂  Mailing Lists"
    url: https://neomutt.org/#mailing-lists
    about: Discuss NeoMutt with other users and developers
