name: Build and Test

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'devel/**'
  workflow_dispatch:

jobs:
  build:
    name: Build-${{ matrix.cfg.name }}
    runs-on: ubuntu-latest
    container: ghcr.io/neomutt/docker-build

    strategy:
      # Limit jobs to one at a time so that ccache really helps later builds
      max-parallel: 1
      matrix:
        cfg:
          - name: default
            options:
          - name: disabled
            options: --disable-idn --disable-nls --disable-pgp --disable-smime --ssl --gsasl
          - name: everything
            options: --autocrypt --bdb --disable-idn --fmemopen --gdbm --gnutls --gpgme --gss --idn2 --kyotocabinet --lmdb --lua --lz4 --mixmaster --notmuch --pcre2 --qdbm --rocksdb --sasl --tdb --tokyocabinet --with-lock=fcntl --zlib --zstd

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Checkout Test Files
      uses: actions/checkout@v3
      with:
        repository: neomutt/neomutt-test-files
        path: test-files

    - name: Set Up Test Files
      run: |
        cd test-files
        ./setup.sh

    - name: Compilation Cache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Configure Neomutt
      run: ./configure --full-doc ${{ matrix.cfg.options }}

    - name: Build Neomutt
      run: make -j 2

    - name: Neomutt Version
      run: ./neomutt -v

    - name: Test Docs
      run: make validate-docs

    - name: Build Tests
      run: make -j 2 test/neomutt-test

    - name: Run Tests
      run: |
        export NEOMUTT_TEST_DIR=$GITHUB_WORKSPACE/test-files
        make test

