name: Centos

on:
  schedule:
    - cron: '30 3 * * 1'
      # Mondays at 03:30
  workflow_dispatch:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        distro:
          - version: 7
          - version: 8
        config:
          - name: Default
            options:
          - name: Minimal
            options: --disable-idn --disable-nls --disable-pgp --disable-smime --ssl --gsasl --with-lock=flock
          - name: Everything
            options: --bdb --full-doc --gnutls --gpgme --gss --lz4 --pcre2 --sasl --tdb --tokyocabinet --with-lock=fcntl --zlib
            options8: --autocrypt --disable-idn --gdbm --idn2 --lua --notmuch --zstd

    name: Centos ${{ matrix.distro.version }} - ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container: ghcr.io/neomutt/centos:${{ matrix.distro.version }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Checkout Test Files
      uses: actions/checkout@v3
      with:
        repository: neomutt/neomutt-test-files
        path: test-files

    - name: Set Up Test Files
      run: |
        cd test-files
        ./setup.sh

    - name: Configure Neomutt
      env:
        OPT_COMMON: ${{ matrix.config.options }}
        OPT_CENTOS8: ${{ matrix.config.options8 }}
      run: |
        OPTIONS="$OPT_COMMON"
        if [ ${{ matrix.distro.version }} = "7" ]; then
          # Centos 7 gpgme workaround
          sed -i '/need 1.4.0/d' auto.def
        else
          # Centos 8 use more options
          OPTIONS="$OPTIONS $OPT_CENTOS8"
        fi
        ./configure $OPTIONS

    - name: Build Neomutt
      run: make -j 2

    - name: Neomutt Version
      run: ./neomutt -v

    - name: Build Tests
      run: make -j 2 test/neomutt-test

    - name: Run Tests
      run: |
        export NEOMUTT_TEST_DIR=$GITHUB_WORKSPACE/test-files
        make test

