name: Fedora

on:
  schedule:
    - cron: '40 3 * * 1'
      # Mondays at 03:40
  workflow_dispatch:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        distro:
          - version: 36
          - version: 37
          - version: 38
        config:
          - name: Default
            options: --testing
          - name: Minimal
            options: --disable-idn --disable-nls --disable-pgp --disable-smime --ssl --gsasl --testing --with-lock=flock
          - name: Everything
            options: --autocrypt --bdb --disable-idn --full-doc --gdbm --gnutls --gpgme --gss --idn2 --lmdb --lua --lz4 --notmuch --pcre2 --qdbm --sasl --tdb --testing --tokyocabinet --with-lock=fcntl --zlib --zstd

    name: Fedora ${{ matrix.distro.version }} - ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container: ghcr.io/neomutt/fedora:${{ matrix.distro.version }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Checkout Test Files
      uses: actions/checkout@v3
      with:
        repository: neomutt/neomutt-test-files
        path: test-files

    - name: Set Up Test Files
      run: |
        cd test-files
        ./setup.sh

    - name: Configure Neomutt
      run: ./configure ${{ matrix.config.options }}

    - name: Build Neomutt
      run: make -j 2 neomutt

    - name: Neomutt Version
      run: ./neomutt -v

    - name: Build Tests
      run: make -j 2 test/neomutt-test

    - name: Run Tests
      run: |
        export NEOMUTT_TEST_DIR=$GITHUB_WORKSPACE/test-files
        make test

