name: macOS

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'devel/**'

env:
  EXTRA_LDFLAGS: "-L/usr/local/opt/ncurses/lib"
  EXTRA_CFLAGS: "-I/usr/local/opt/ncurses/include"

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Compilation Cache
      uses: hendrikmuhs/ccache-action@v1

    # - name: Install Homebrew dependencies
      # run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install ncurses && brew info ncurses

    - name: Configure Neomutt
      run: ./configure --disable-doc --disable-nls

    - name: Build Neomutt
      run: make -j 2 neomutt

    - name: Neomutt Version
      run: ./neomutt -v
